# ---- Appearance ----
set -g mouse on
set -g xterm-keys on
set -g mode-keys vi
setw -g monitor-activity on
set -g history-limit 100000
set -g display-time 4000
set -g allow-passthrough on
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",xterm-kitty:Tc"
set -as terminal-features ',xterm-kitty:hyperlinks'


# Hide bottom status bar and remove green default theme
set -g status off
set -g status-style bg=default,fg=default
set -g pane-border-style fg=colour238
set -g pane-active-border-style fg=colour238
set -g pane-border-status off





# ---- Key bindings ----
unbind C-b                          # Remove default prefix
set -g prefix C-Space               # Use Ctrl+Space
bind C-Space send-prefix

# Splits
bind [ split-window -h
bind - split-window -v
unbind '"'
unbind %

# Close split pane
bind-key -n C-w kill-pane          

# Switch panes with Alt+arrow keys
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Reload tmux config
bind r source-file ~/.tmux.conf \; display "Reloaded tmux.conf"

# Fix Ctrl+Left / Ctrl+Right word movement
bind -n C-Left send-keys M-b
bind -n C-Right send-keys M-f

# Enter copy-mode on PageUp/PageDown and keep scrolling
bind -n PageUp if -F "#{pane_in_mode}" "send-keys -X page-up" "copy-mode -e; send-keys -X page-up"
bind -n PageDown if -F "#{pane_in_mode}" "send-keys -X page-down" "copy-mode -e; send-keys -X page-down"

# Set title automatically to: <session_name>:<window_name>
set -g set-titles on
set -g set-titles-string '#S:#W'



# --- Plugins ---

# > Tmux Plugin Manager
set -g @plugin 'tmux-plugins/tpm'

# > Tmux Resurrect (save & restore)
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-capture-pane-contents 'on'    # Save shell history also

# > Tmux Continuum (automated restore)
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-save-interval '10'            # Auto-save every 10 min
set -g @continuum-restore 'on'                  # Auto-restore on restart

# Initialize TPM
run '~/.tmux/plugins/tpm/tpm'
